<?xml version="1.0" encoding="utf-8"?><Database Name="CafeJavaDatabase" Class="db_classesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CafeJavaDatabase.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="Caffe_7_1_3.Properties.Settings" SettingsPropertyName="CafeJavaDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Items" Member="StoreItems">
    <Type Name="StoreItems">
      <Column Name="ItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ItemCountInInventory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>